### ISSUE TITLE
Update code 

### ISSUE THREAD

**Issue by andygup** [Esri/html5-geolocation-tool-js#1]
Update to latest JS API and implement jQueryHelper library.

**Comment by remmi11** [comment]
App works perfectly in web browser. However using build.phonegap.com  and preparing app for iOS device I am experiencing two issues.

First the CSS components do not seem to have loaded.

Secondly although location is turned on on the device the app displays Geo: OFF?

This may be a phonegap issue? Has anybody successfully implemented on iphone?

**Comment by andygup** [comment]
@remmi11 Ah, gotcha, sorry I thought you'd already taken steps to modify this repo's app to work in PhoneGap. Note that an app that's configured correctly to run in the browser typically won't run in PhoneGap/Cordova. PhoneGap JavaScript apps have to follow a very specific event-based life-cycle. 

Here's another repo you might check out that has examples specifically built to work in PhoneGap: https://github.com/Esri/quickstart-map-phonegap. That repo contains several basic Geolocation samples including: https://github.com/Esri/quickstart-map-phonegap/blob/master/index_jquerymobilegps.html. 

Let me know if that helps?

**Comment by Kayoti** [comment]
The other repo does not have location accuracy calculation. I really need to run your geolocation test app on native platform using phone gap :(

**Comment by andygup** [comment]
Correct, the quickstart-map-phonegap repo is intended to be provide only simple demonstration examples and lay the foundation for devs that want to build larger applications. 

Is there a technical issue why you aren't able to get either of the test apps from this repo running in PhoneGap? 

Here's some additional info since I've had many people ask if PhoneGap provides additional geolocation functionality above and beyond what you'd get in the device's browser. The short answer: there is no difference. If the device provides altitude information, for example, you can get that via the browser or via PhoneGap. The device browser can also provide offline GPS data, so there's no specific requirement to use PhoneGap to get offline GPS readings.

**Comment by Kayoti** [comment]
so in short I will get the same accuracy weather im using native location api's or browser? the reason why I wanted to use your app on native platforms is to test the accuracy of native api's vs browser location services.

**Comment by andygup** [comment]
@Kayoti Yes, the GPS accuracy should be the same whether you are reading it via the browser Geolocation API or via the native Location APIs. 

For others that are reading this, here is some additional background reference sources. In theory, these APIs should simply be passing thru the raw GPS location data. For example, in the [W3C Geolocation API Spec. Section 2 [paragraph 1]](http://dev.w3.org/geo/api/spec-source.html#introduction) it says "The API itself is agnostic of the underlying location information sources."

However, you mention "location services." There will be differences in accuracy between raw locations provided by the GPS and locations that were retrieved via the Location Services. These are two different things. Here's a blog post I wrote on that topic for reference: [HTML5 Geolocation API – how accurate is it, really?](http://www.andygup.net/html5-geolocation-api-%E2%80%93-how-accurate-is-it-really/).

One important note: there is a distinct advantage to the native Android SDK in that it offers the capabilities for determining specifically which source is sending the location data: [GPS_PROVIDER](http://developer.android.com/reference/android/location/LocationManager.html#GPS_PROVIDER) or [NETWORK PROVIDER](http://developer.android.com/reference/android/location/LocationManager.html#NETWORK_PROVIDER).

This native Android [Location Strategies](http://developer.android.com/guide/topics/location/strategies.html) doc is also a good read.
