### ISSUE TITLE
Any methods to detect geolocation spoofing? 

### ISSUE THREAD

**Issue by jasan-s** [Esri/html5-geolocation-tool-js#30]
I have been searching online for established methods for checking for geolocation spoofing but could not find any detailed explanation of the techniques. One comment on StackOverflow suggested to detect  extreme speed or distance changes but Isn't that also spoofable and how to account for the case when user spoofs directly to the location and then turns on the app.

**Comment by andygup** [comment]
There's no fool proof way for a web app to check for spoofing that I'm aware of. The data provided by the browser's Geolocation API is too limited, and of course the use case you mentioned.

You'd really need either a native or hybrid Android app for this use case. Cordova-based Android apps can gather cellular network information, if it's available, and then try to verify it against a cell tower database. Getting the network info can be accomplished thru plugins such as [cordova-plugin-advanced-geolocation](https://github.com/Esri/cordova-plugin-advanced-geolocation) and there are a variety of cell tower database providers some of which are more up-to-date than others.

**Comment by andygup** [comment]
I'm going to close this out. If you need to reopen it please feel free to do so.
